name: hatim
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: 3.3.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  hive: ^2.2.3
  infinite_scroll_pagination: ^3.2.0
  path_provider: ^2.0.11
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.21.4
  very_good_analysis: ^3.1.0 # linter for our app
  mocktail: ^0.3.0
  build_runner:
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/constants/assets/  # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true  
