name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: "stable"
      - run: flutter doctor
      - run: flutter pub get

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: default
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --target=test_driver/app.dart
      # # Integration test
      # - run: flutter drive --target=test_driver/app.dart
