name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios:
    strategy:
      matrix:
        device:
          - "iPhone 11 Simulator (15.2)"
      fail-fast: true
    runs-on: macos-11
    steps:
      - name: "List all simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        run: flutter test integration_test --verbose

  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test --verbose
# jobs:
#   drive_android:
#     runs-on: macos-latest
#     strategy:
#       matrix:
#         api-level: [30]
#     steps:
#       - uses: actions/checkout@v2
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: "3.3.9"
#           channel: "stable"

#       # Run integration test
#       - name: Run Flutter Driver tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           target: ${{ matrix.target }}
#           api-level: ${{ matrix.api-level }}
#           arch: x86_64
#           profile: Nexus 6
#           script: ./scripts/ci_android.sh

# Update screenshot to artifact
# - name: Upload screenshots
#   if: always()
#   uses: actions/upload-artifact@v1
#   with:
#     name: screenshot
#     path: ${{ matrix.path }}screenshots/
# jobs:
#   integration_test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v2
#         with:
#           distribution: "zulu"
#           java-version: "11"
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.3.9"
#           channel: "stable"
#       - run: flutter doctor
#       - run: flutter pub get

#       # Run integration test
#       - name: Run Flutter Driver tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           target: default
#           api-level: 30
#           arch: x86_64
#           profile: Nexus 6
#           script: ./scripts/ci_android.sh
#       # # Integration test
#       # - run: flutter drive --target=test_driver/app.dart
