name: CI IOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios:
    strategy:
      matrix:
        device:
          - "iPhone 11 Simulator (15.2)"
      fail-fast: true
    runs-on: macos-11
    steps:
      - name: "List all simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        run: flutter drive --target=test_driver/app.dart
